stages:
  - build
  - tag

before_script:
  - |
    export ENV_NAME=$(echo $CI_COMMIT_REF_SLUG | cut -d- -f1)

build:
  stage: build
  tags:
    - docker-builder
  script: |
    docker build --pull --force-rm --cpu-shares=512 --memory 512MB --memory-swap 720MB -t $CI_REGISTRY_IMAGE:$ENV_NAME --label "rev=$CI_COMMIT_SHA" .
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    docker push $CI_REGISTRY_IMAGE:$ENV_NAME
  only:
    - master
    - develop
    - staging
    - /^[a-z]+-[0-9]+$/

tag-staging:
  stage: tag
  tags:
    - docker-builder
  script: |
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    docker pull $CI_REGISTRY_IMAGE:$ENV_NAME
    docker push $CI_REGISTRY_IMAGE:staging
  when: manual
  only:
    - develop

tag-live:
  stage: tag
  tags:
    - docker-builder
  script: |
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    docker pull $CI_REGISTRY_IMAGE:$ENV_NAME
    docker push $CI_REGISTRY_IMAGE:live
  when: manual
  only:
    - develop
    - master