version: '2.1'

networks:
  mysql:
    external:
      name: mysql

  proxy:
    external:
      name: proxy

services:
  memcached:
    image: memcached

  policatphp:
    image: webvariants/php:7.2-fpm-alpine
    depends_on:
        - memcached
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "./:/app"
    tmpfs:
      - "$HOME"
    working_dir: "/app"
    networks:
      - mysql
      - default
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    environment:
      PHP_IMAGE_VERSION: "2"
      WEB_ROOT: "/app/web"
      WWW_USER: "${WWW_USER:-martin}"
      WWW_GROUP: "${WWW_GROUP:-martin}"
      PHPINI_SESSION__GC_MAXLIFETIME: "3600"

  # policatphp:
  #   build: .
  #   depends_on:
  #       - memcached
  #   volumes:
  #     - /etc/passwd:/etc/passwd:ro
  #     - /etc/group:/etc/group:ro
  #     - "./data:/app/data"
  #     - "./config:/app/data/config:ro"
  #   user: "${USER_UID:-1000}:${USER_GID:-1000}"
  #   tmpfs:
  #     - /app/cache
  #     - /app/log
  #   networks:
  #     - mysql
  #     - default
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - NET_BIND_SERVICE

  main:
    image: webvariants/nginx-acme-and-more
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/app"
    tmpfs:
      - /tmp
    networks:
      - proxy
      - default
    depends_on:
      - policatphp
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${HOST:-policat.local}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=${NETWORK:-proxy}
