all:
  http_metas: []

  metas:
    title:        ''
    robots:       index, follow
    charset: utf8

  stylesheets:    [opt]

  javascripts:    [html5: { condition: lt IE 9 }, opt]

  has_layout:     true
  layout:         dashboard
