all:
  http_metas: []

  metas:
    title:        ''
    robots:       index, follow
    charset: utf8

  stylesheets:    [dist/frontend4: { media: 'all' }, dist/frontend_print: { media: print }, "dist/bootstrap4.min.css", "dist/bootstrap-custom.css"]

  javascripts:    ["dist/frontend", "dist/jquery-3.1.min.js", "dist/tether.min.js", "dist/bootstrap4.min.js"]

  has_layout:     true
  layout:         bootstrap4
