default:
  http_metas:
    content-type: text/html

  metas:
    title:        policat.org
    description:  'Policat: Poli-Cyber-Action-Tool'
    keywords:     policat, petition, e-action, e-petition, e-petiton-tool, cyberaction, cyberaction-tool
#    language:     en
    robots:       index, follow

  stylesheets:    ["dist/bootstrap4.min.css", "dist/bootstrap-custom.css", dist/frontend4: { media: 'all' }, dist/frontend_print: { media: print }]

#  javascripts:    ["dist/jquery-3.1.min.js", "dist/tether.min.js", "dist/popper.min.js", "dist/bootstrap4.min.js", "dist/frontend"]

  has_layout:     true
  layout:         layout
