index:
  enabled: true
  lifetime: 60

indexB4:
  enabled: true
  lifetime: 60

tips:
  enabled: true

terms:
  enabled: true

contact:
  enabled: true

_footer:
  enabled: true

_footerB4:
  enabled: true

_home_menu:
  enabled: false