<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version210 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'timezone', 'string', '30', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'timezone');
    }
}